Only fail one of the regions

diff --git a/.github/workflows/acceptance-test-multi-region.yml b/.github/workflows/acceptance-test-multi-region.yml
--- a/.github/workflows/acceptance-test-multi-region.yml
+++ b/.github/workflows/acceptance-test-multi-region.yml
@@ -98,8 +98,13 @@ jobs:
     timeout-minutes: 180
 
     steps:
-      - name: Succeed intentionally
-        run: exit 0
+      - name: Fail conditionally
+        run: |
+          if [[ "${{ matrix.region }}" == "AP" ]]; then
+            exit 1
+          else
+            echo "Skipping failure for region ${{ matrix.region }}"
+          fi
 
   # run acceptance tests in a matrix with Terraform core versions and regions
   # flaky flag set
