Test fail in third step

diff --git a/.github/workflows/test-slack-webhook.yml b/.github/workflows/test-slack-webhook.yml
--- a/.github/workflows/test-slack-webhook.yml
+++ b/.github/workflows/test-slack-webhook.yml
@@ -21,10 +21,6 @@ jobs:
     - name: Prepare
       run: |
         echo "Prepare"
-    - name: Fail
-      run: |
-        echo "Fail"
-        exit 1
   test:
     name: Test
     runs-on: ubuntu-latest
@@ -33,6 +29,10 @@ jobs:
     - name: Test
       run: |
         echo "Test"
+    - name: Fail
+      run: |
+        echo "Fail"
+        exit 1
   test-flaky:
     name: Test Flaky
     runs-on: ubuntu-latest
