Fail on second step

diff --git a/.github/workflows/test-slack-webhook.yml b/.github/workflows/test-slack-webhook.yml
--- a/.github/workflows/test-slack-webhook.yml
+++ b/.github/workflows/test-slack-webhook.yml
@@ -13,10 +13,6 @@ jobs:
     - name: Build
       run: |
         echo "Build"
-    - name: Fail
-      run: |
-        echo "Fail"
-        exit 1
   prepare:
     name: Prepare
     runs-on: ubuntu-latest
@@ -25,6 +21,10 @@ jobs:
     - name: Prepare
       run: |
         echo "Prepare"
+    - name: Fail
+      run: |
+        echo "Fail"
+        exit 1
   test:
     name: Test
     runs-on: ubuntu-latest
